# environment.yml
name: boap
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - nanoq=0.10.0
  - raven-assembler=1.8.3
  - filtlong=0.3.1
  - flye=0.9.6
  - dnaapler=1.3.0
  - seqkit=2.12.0
  - medaka=2.2.0
  - python=3.90
  - scipy=1.17.0
  - samtools=1.23
