name: boap
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - nanoq=0.10.0
  - raven-assembler=1.8.3
  - filtlong=0.3.1
  - flye=2.9.6
  - dnaapler=1.3.0
  - seqkit=2.12.0
  - medaka=2.2.0
  - scipy=1.17.0
